name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        check-latest: true
        cache: maven


    - name: Grant execute permission to MVN Wrapper
      run: chmod +x ./mvnw

    - name: Build and analyze
      run: ./mvnw -B verify